SHELL := /bin/bash
.ONESHELL:
.SHELLFLAGS := -eu -c

JDK17_HOME := /usr/lib/jvm/java-17-openjdk-amd64
DCM4CHE_DIR := $(CURDIR)/vendor/dcm4che
ASSEMBLY_TARGET := $(DCM4CHE_DIR)/dcm4che-assembly/target
DCM4CHE_GIT := https://github.com/dcm4che/dcm4che.git
DCM4CHE_BRANCH := master

.PHONY: all prereq java fetch build unzip env clean help

all: prereq java fetch build unzip env

help:
	@echo "make all -> Java17 + fetch dcm4che + build bin distro + env.sh"
	@echo "Then: source env.sh ; dcm2jpg -h"

prereq:
	echo "[Prereq] Handling Yarn apt repo if it breaks apt-get update..."
	if [ -f /etc/apt/sources.list.d/yarn.list ]; then \
	  sudo sed -i 's/^[[:space:]]*deb /# deb /' /etc/apt/sources.list.d/yarn.list || true; \
	fi

java:
	echo "[Java] apt-get update..."
	sudo apt-get update
	echo "[Java] Installing OpenJDK 17..."
	sudo apt-get install -y openjdk-17-jdk unzip git
	sudo update-alternatives --set java  $(JDK17_HOME)/bin/java || true
	sudo update-alternatives --set javac $(JDK17_HOME)/bin/javac || true
	export JAVA_HOME=$(JDK17_HOME)
	export PATH="$$JAVA_HOME/bin:/usr/bin:$$PATH"
	hash -r
	java -version
	javac -version

fetch:
	echo "[Fetch] Ensuring dcm4che sources exist in $(DCM4CHE_DIR)..."
	mkdir -p $(CURDIR)/vendor
	if [ ! -d "$(DCM4CHE_DIR)/.git" ]; then \
	  git clone --depth 1 -b $(DCM4CHE_BRANCH) $(DCM4CHE_GIT) "$(DCM4CHE_DIR)"; \
	else \
	  echo "  - dcm4che repo already present"; \
	fi

build:
	echo "[Build] Building dcm4che assembly..."
	cd "$(DCM4CHE_DIR)"
	export JAVA_HOME=$(JDK17_HOME)
	export PATH="$$JAVA_HOME/bin:/usr/bin:$$PATH"
	./mvnw -DskipTests install -pl dcm4che-assembly -am

unzip:
	echo "[Unzip] Extracting dcm4che distribution..."
	cd "$(ASSEMBLY_TARGET)"
	ZIP=$$(ls -1 dcm4che-*-bin.zip | head -n 1)
	unzip -o "$$ZIP" >/dev/null
	ls -d dcm4che-*/bin | head -n 1

env:
	echo "[Env] Generating env.sh..."
	BIN_DIR=$$(ls -d "$(ASSEMBLY_TARGET)"/dcm4che-*/bin | head -n 1)
	echo "# Auto-generated by Makefile" > env.sh
	echo "export DCM4CHE_BIN=\"$$BIN_DIR\"" >> env.sh
	echo "export PATH=\"\$$DCM4CHE_BIN:\$$PATH\"" >> env.sh
	echo "hash -r" >> env.sh
	chmod +x env.sh
	echo "✅ env.sh created."
	echo "Run: source env.sh && dcm2jpg -h"

clean:
	rm -rf vendor/dcm4che
	rm -f env.sh
